### ISSUE TITLE
File resources assume specific umask

### ISSUE THREAD

**Issue by jcmcken** [theforeman/puppet-puppet#111]
There are a few ``file`` resources throughout the module that assume a permissive umask (e.g. ``0022``). Many security benchmarks suggest a more restrictive default umask (e.g. ``0027``). On such systems, this module will break with various files inaccessible by ``apache`` (e.g. ``/etc/puppet/rack`` and its contents).

**Comment by mmoll** [comment]
is this still an issue?

**Comment by domcleal** [comment]
I don't think so, since the file resources managing *files* should ignore umasks.  Directory file resources should no longer follow the umask, I fixed instances of these a little while ago.

**Comment by ekohl** [comment]
Since https://github.com/theforeman/puppet-puppet/commit/a8db30aa2cbd03a673ff46e7728f5f1adc1d4457 I think we have explicit permissions on all files so I agree this should be fixed.
