### ISSUE TITLE
Puppet server certificate generation improvements?

### ISSUE THREAD

**Issue by jcmcken** [theforeman/puppet-puppet#113]
We have a multi-puppetmaster environment with a separate CA server and are running into some issues with the cert generation @ https://github.com/theforeman/puppet-puppet/blob/master/manifests/server/config.pp#L61 

Specifically, we updated the module so that:

* The certificate should only be generated if the host is a CA (``$::puppet::server_ca`` is ``true``). Currently, all puppet servers will generate a self-signed cert.
* If a ``$::puppet::ca_server`` is specified, and it is not equal to ``$::fqdn``, the certificate should be generated with a DNS alt name == ``$::puppet::ca_server``. 

What do you think?

**Comment by mmoll** [comment]
@jcmcken was there a PR for this?

**Comment by whefter** [comment]
Additional problem I've noticed: when cascading Puppetmasters (don't ask), then running `puppet cert --generate $::fqdn` does NOT generate a CA since `/var/lib/puppet/ssl/certs/ca.pem` is already present. To generate a new CA, `puppet cert list` will then do.

**Comment by mmoll** [comment]
can this get closed as #314 went in?

**Comment by mmoll** [comment]
no reaction, closing.
