### ISSUE TITLE
puppet.conf not readable by puppet

### ISSUE THREAD

**Issue by lfisher47** [theforeman/puppet-puppet#137]
When the system umask is 077, the puppet.conf file is owned by root and has perms of 0600 so the foreman-proxy and puppet server can't read the puppet.conf file.

**Comment by mmoll** [comment]
is this still an issue?

**Comment by lfisher47** [comment]
No, it looks like I fixed it but didn't get the code attached to the issue.

**Comment by mmoll** [comment]
thanks!
