### ISSUE TITLE
creating a puppetmaster when puppet client is already managed

### ISSUE THREAD

**Issue by neoice** [theforeman/puppet-puppet#170]
I have something very similar to the following:

```puppet
# this role is applied *globally*
class role::base {
  include 'company_puppet::base'
  # sshd config, system config, monitoring agents, etc
}

# this role is only applied to the puppetmasters
class role::puppetmaster {
  include 'company_puppet::server'
}

# straight forward: install puppet using theforeman/puppet-puppet and twiddle some settings for puppetctl
# https://github.com/theforeman/puppet-puppet
# https://github.com/mozilla-it/puppetctl
class company_puppet::base {
  class { '::puppet':
    runmode             => 'cron',
    cron_cmd            => 'if test -f /var/lib/puppet/state/disabled.at; then exit 0; else /usr/bin/puppet agent --onetime --no-daemonize --logdest syslog > /dev/null 2>&1 ; fi',
    show_diff           => true,
  }
}

# try and override our base class with additional parameters.
# instead, the "[master]" section of `/etc/puppet/puppet.conf` will be removed!
class company_puppet::server inherits company_puppet::base {
  Class ['::puppet'] {
    server                      => true,
    dns_alt_names               => ["puppet.${environment}"],
    server_storeconfigs_backend => 'puppetdb',
    server_environments         => [],
    server_template             => 'company/puppetmaster_server.conf.erb',
    server_facts                => false,
    server_foreman_url          => "https://foreman.${environment}",
  }
  # a bunch more uninteresting stuff goes here
}
```

the intent is that **all** hosts in the fleet receive `role::base` and then one or more "service" roles, like `role::puppetmaster`. I have been unable to get this to work using the theforeman/puppet-puppet module.

I know that Puppet inheritance is weird and limited, so I suspect what I'm doing may not be possible via this mechanism. there's a particularly disturbing note here: http://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#inheritance

> Note: If a base class declares other classes with the resource-like syntax, a class derived from it cannot override the class parameters of those inner classes. This is a known bug.

I think I **could** solve this by using parameters in TheForeman, but I prefer to keep as much data in our `roles` as possible and use TheForeman for environment data (test vs prod).

**Comment by martinpfeifer** [comment]
As you already pointed out correctly it is (currently) not possible to overwrite class parameters through inheritance.
I think the problem here is that the module manages two not necessary related things: the puppet agent and the puppet master. A solution could be to split the agent and master parts in separate subclasses puppet::agent and puppet::master with the appropriate set of parameters and inherit from puppet::params instead of switching behaviour via a parameter.

**Comment by domcleal** [comment]
It did used to be in two separate classes :)  Unfortunately that also has its own problems as many of the configuration files are shared between the two services and we found the module was very unreliable as a result, hence the rewrite to a single top-level class.

**Comment by ekohl** [comment]
Note that you can set all the server parameters except `server` itself in the base profile and then simply include `puppet::server` in your ```company_puppet::server``` class.

**Comment by martinpfeifer** [comment]
@domcleal: Oh sorry, didn't check for that.
@ekohl: Jap, that works. Really embarrassing that i didn't think of that earlier :(

**Comment by mmoll** [comment]
is OK to close this issue?

**Comment by martinpfeifer** [comment]
Fine with me.
