### ISSUE TITLE
Key file ownership constantly changed

### ISSUE THREAD

**Issue by raphink** [theforeman/puppet-puppet#192]
The `puppet::server::config` class manages the group for the host's private key. This also sets the owner to `root` by default. However, Puppet 3.7.1 (maybe older too?) sets it to `puppet` when starting.

This causes the ownership of the file to be changed for each run:

```
Notice: /Stage[main]/Puppet::Server::Config/File[/var/lib/puppet/ssl/private_keys]/owner: owner changed 'puppet' to 'root'
Notice: /Stage[main]/Puppet::Server::Config/File[/var/lib/puppet/ssl/private_keys/foo.example.com.pem]/owner: owner changed 'puppet' to 'root'
```

**Comment by mmoll** [comment]
is this still an issue?

**Comment by mmoll** [comment]
@raphink ping?

**Comment by raphink** [comment]
@mmoll we no longer use this module, so I can't tell you if the issue is still there.

**Comment by mmoll** [comment]
@raphink sad to hear that :cry:, but thanks for the note. Closing as there seems no other reports about this.
