### ISSUE TITLE
foreman-installer doesn't add ssl options in puppet.conf for master

### ISSUE THREAD

**Issue by logicminds** [theforeman/puppet-puppet#197]
I just ran the foreman installer and assuming this is the module that generated the puppet.conf for the master configuration.  It seems like there are some missing options when puppet master is run under apache.  Since the installer configures the master to run under apache the following lines need to be added to the puppet master configuration file.

Options included
```
foreman-installer --enable-foreman-compute-ec2 --enable-foreman-compute-gce --enable-foreman-compute-ovirt --enable-foreman-compute-vmware --enable-puppet --puppet-server-envs-dir=/etc/puppet/environments --puppet-server-environments=test
```

Necessary options to add to the puppet master conf
```
   ssl_client_header = SSL_CLIENT_S_DN
   ssl_client_verify_header = SSL_CLIENT_VERIFY
```

This causes the following error:
```shell
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: [self signed certificate in certificate chain for /CN=Puppet CA: puppet_master.company.com]
```

**Comment by mmoll** [comment]
Not sure what went wrong there, is this reproducible on a clean machine? I did some test setups in the last days by running foreman-installer without options, which also defaults to install a puppet master under apache/passenger and it always worked for me.

**Comment by logicminds** [comment]
This was on a OEL 6.5 machine.  A few more install problems were missing like the scl ruby did not install either because the yum repo did not exist to install it from.  What OS did you try it on?

**Comment by mmoll** [comment]
Debian/wheezy mainly and one time on CentOS 7, but in the past also CentOS 6.

**Comment by mmoll** [comment]
Just tested with CentOS 6.6 server and client, no problems... If you can reproduce this on OEL, have a look in the foreman-installer logfile, I don't want to rule out some osfamily conversion missing somewhere...

**Comment by ekohl** [comment]
We use https://github.com/mcanevet/rspec-puppet-facts which doesn't have facts for OEL. It could be helpful to have a set of (anonymized) facts to test against.

**Comment by mmoll** [comment]
@logicminds any news on this?

**Comment by logicminds** [comment]
no, a bit slammed.  I need to test out a foreman plugin which requires a foreman server so I will try it soon.

**Comment by mmoll** [comment]
@logicminds any news on this?

**Comment by logicminds** [comment]
will close for now, and reopen if I see it again.
