### ISSUE TITLE
can't configure "reporturl" from module

### ISSUE THREAD

**Issue by confiq** [theforeman/puppet-puppet#221]
`reporturl` might be called [hidden feature](https://docs.puppetlabs.com/dashboard/manual/1.2/bootstrapping.html) but if I'm not wrong, this module is not supporting it without using custom `server_template`.

If needed, I can make PR but the question is, do we need such a feature?

**Comment by domcleal** [comment]
IIRC it's used with regular HTTP uploads of reports to some external dashboard.  Foreman no longer supports that API - we have our own report processor and a customised API so we could shift some of the processing to the Puppet master - only Puppet Dashboard does.

I don't mind adding it, but I'd be surprised if there are many Dashboard users using this module :smile:

**Comment by confiq** [comment]
> I'd be surprised if there are many Dashboard users using this module

:)
I would be surprised if there are any Dashboards users left. The reason why we are using this module is to make immigration to foreman easier (in case we decide).
Anyway, this should be easy "_fix_". I'll try to find free time during this/next week to make it happen unless someone objects ?

Cheers

**Comment by ekohl** [comment]
Since we concat it, you could also create your own concat fragment if it's a one-off migration. I don't mind adding it though though I would prefer to have it properly documented that reporturl is for the old puppet dashboard and not foreman.

**Comment by confiq** [comment]
>  create your own concat fragment if it's a one-off migration

Can you elaborate more? Instead `puppet.conf+30-master` to put it in new concat fragment?
It's probably not what you meant cause `reporturl` should be in [master] section. 
I was thinking to add new argument to class `puppet::params` and if condition in template.

**Comment by ekohl** [comment]
Adding it as a parameter will certainly work, but you can create a ```puppet.conf+31-reporturl``` fragment to add it in the master section. ```puppet.conf+*``` will be concatted alphabetically and since you know 30 will be the master section, 31 will be added after it. In the same way you can use 21-29 for agent parts and 11-19 for main parts.

**Comment by confiq** [comment]
>but you can create a puppet.conf+31-reporturl fragment to add it in the master section. puppet.conf+*

I think that would be very useful if we could use from global scope. Ex:

```puppet
concat_fragment { 'puppet.conf+31-reporturl':
    content => template('reporturl = http://foo'),
  }
class { '::puppet': server => true }
```

(Un)fortunately this will not work. And putting new concatenation segment only for one line of [master] section seems overkill for me. 

Let's put it this way, I'll make PR asap and we'll review it there.

Cheers

**Comment by ekohl** [comment]
Won't this work? Note that I didn't add ```template()```
```puppet
concat_fragment { 'puppet.conf+31-reporturl':
  content => 'reporturl = http://foo',
}
```

**Comment by confiq** [comment]
ohh ****, `template()` was a mistake, that's why it didn't work.
We got 3 options:
* Make little dev+docs for this (new param & _if_ in template)
* Make docs for this (it might be I missed it?)
* Status quo and close this issue.

What do you prefer?

**Comment by domcleal** [comment]
Maybe documenting the use of concat is best?  Then it'll help a whole load of people add options when they're not available as parameters.

I just remembered we also have the `$server_additional_settings` hash of additional parameters for the `[master]` config section.  (No corresponding parameters for `[main]` or `[agent]` yet.)

**Comment by ekohl** [comment]
While I was typing, @domcleal wrote what I wanted to write.

**Comment by confiq** [comment]
Agree, documenting `concat_fragment` is best option.
Feel free to close the issue.
Cheers

**Comment by confiq** [comment]
I'll be nice and I'll close the issue. 
Thanks guys

**Comment by domcleal** [comment]
Heh, thanks!
