### ISSUE TITLE
add code for configuring for 'puppet kick'

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-puppet#247]
per http://projects.theforeman.org/projects/foreman/wiki/Puppetrun

There are a few settings required to enable Foreman's ability to run puppet on remote hosts.

Can the relevant behavior be added to this module so that I can use the Foreman puppet agent configuration module and enable this behavior all at once?

**Comment by ekohl** [comment]
puppet kick is deprecated in favour of mcollective, but that's certainly out of scope. @domcleal what do you think?

**Comment by domcleal** [comment]
We already have `listen` and `listen_to` parameters which should do this.  Enable the former and the puppet master will be permitted to kick the agent.

**Comment by jcpunk** [comment]
That works, didn't see how to pass those to the module.
