### ISSUE TITLE
Directory environments sub directory's should allow for condidtionally creation.

### ISSUE THREAD

**Issue by gapotts** [theforeman/puppet-puppet#254]
When you automatically create directories under $confdir/environments you break R10K's ability to create and populate those directories.

I used the following snippet to create my puppet server.

class { '::puppet':
  server                => true,
  server_foreman        => false,
  server_reports        => 'store',
  server_external_nodes => '',
}
Then initialized R10K using Zack's R10K module. By default /etc/puppet/environment/production exists and contains a manifests & modules directory by way of your module, so when I run r10k deploy environment -pv it errors out with the following:
==> puppet.example.com: Command: git clone --reference /var/cache/r10k/https---github.com-gapotts-r10k-ctl-mmpup.git https://github.com/gapotts/r10k-ctl-mmpup.git /etc/puppet/environments/production
==> puppet.example.com: Stderr:
==> puppet.example.com: fatal: destination path '/etc/puppet/environments/production' already exists and is not an empty directory.
==> puppet.example.com: Exit code: 128

For those of us who plan on using R10K this will become problematic.

Regards -Greg

**Comment by mmoll** [comment]
I suppose a boolean parameter to control that behaviour would be OK? Could you implement that and open a pull request (or just tell us, if not)? :)

**Comment by gapotts** [comment]
I actually found by setting 'server_environments => []’ Fixed the problem. So no code change needed. Just add that to the Docs for when R10K is in play.

Regards -Greg

**Comment by mmoll** [comment]
@ekohl your opinion in that? That workaround doesn't feel right to me, at the other hand, we might have to rethink defaults in this module as puppet behaviour changes over the versions...

**Comment by ekohl** [comment]
If you're using r10k, why not set ```$puppet::server_dynamic_environments``` to ```true```? We should consider making that the default because I believe that is what most people want.

**Comment by gapotts** [comment]
From Module’s own comment section:
# $server_dynamic_environments:: Use $environment in the modulepath
# Deprecated when $server_directory_environments is true,
# set $server_environments to [] instead.
# type:boolean

**Comment by mmoll** [comment]
OK, I see... @gapotts could you open a pull request to the README.md file?

**Comment by gapotts** [comment]
See pull request https://github.com/theforeman/puppet-puppet/pull/255

**Comment by ekohl** [comment]
Since #255 was merged, I'm closing this. Thanks!
