### ISSUE TITLE
Configuring fileserver.conf and auth.conf

### ISSUE THREAD

**Issue by confiq** [theforeman/puppet-puppet#257]
Unless I missed something in code/docs, at a moment we are unable to edit `fileserver.conf` and file `auth.conf` is hardcoded in template/ . 
The question is, is there any plans to make it configurable or it is like this for specific reasons?
Do we need PR for this?

Regards

**Comment by ekohl** [comment]
I think the only reason is that so far it hasn't been requested.

**Comment by mmoll** [comment]
Same here, we would of course welcome a PR for that :)

**Comment by confiq** [comment]
Ok, I'll try to PR this weekend.

**Comment by mmoll** [comment]
@confiq what's the status here? :)

**Comment by confiq** [comment]
Due lack of time, I'll close this issue :(
