### ISSUE TITLE
Impossible not to use ENC with future parser

### ISSUE THREAD

**Issue by halfninja** [theforeman/puppet-puppet#262]
I don't seem to be able to set `$::puppet::server_external_nodes` to a value that uses the plain terminus instead of exec. The `puppet` class checks that this value is a string, so I can't pass in `false`, but all strings in the future parser evaluate to true. Passing `undef` to `puppet` means the default param is used.

Could parameters that take a boolean be a bit more lenient about allowing actual booleans as well as strings that look like booleans?

**Comment by mmoll** [comment]
Please see #250 and theforeman/foreman-installer-modulesync#11 for future parser work regarding this module. Help welcome! :)

**Comment by halfninja** [comment]
Cool, I'll take a look
