### ISSUE TITLE
Allow setting of JAVA_ARGS for puppetserver

### ISSUE THREAD

**Issue by petems** [theforeman/puppet-puppet#274]
Basically something like this: https://github.com/camptocamp/puppet-puppetserver/blob/master/manifests/config/java_arg.pp

Otherwise depending on the memory of your server, trying to setup Foreman using the default setting (which I think is 2GB?) on a box lower than that default gives out of memory errors :+1:

**Comment by mmoll** [comment]
Indeed, just ran into this. :rotating_light:
Mind sending a PR? :)
