### ISSUE TITLE
Incomplete SSL Configuration

### ISSUE THREAD

**Issue by discreet** [theforeman/puppet-puppet#275]
When using the foreman-installer to change from puppet master to puppet server everything completes without error. However when running a puppet agent SSL errors are seen. Through some troubleshooting it seems as if /etc/puppetserver/bootstrap.cfg remained configured to have the puppet server act as the CA. I personally use an external CA so I had to change this configuration. I also had to modify /etc/puppetserver/conf.d/webserver.conf to include the ssl certificate information (cert, key, ca) in order to have successful agent runs.

**Comment by jyaworski** [comment]
I also have this issue.

**Comment by mmoll** [comment]
As always, PRs would be highly welcome, the documentation regarding that should be covered in https://docs.puppetlabs.com/puppetserver/1.1/puppet_conf_setting_diffs.html

As @mcanevet already pointed out in one of his PRs, it might be worth checking out what's already there in https://github.com/camptocamp/puppet-puppetserver and maybe use this module/reuse code/merge this module in theforeman-puppet.

Ideally, it already should also be taken care of differences between AIO and non-AIO builds, but having puppetserver 1.1 fully supported would already be great.

**Comment by pall-valmundsson** [comment]
I'm interested in this as well. Which way would you like to go, call and depend the camptocamp module or merge the relevant bits into this module?

**Comment by mmoll** [comment]
I'd like to see the relevant code come into this module here, be it from the cryptocamp module or some other approach (e.g. using puppetlabs-hocon), but that's only my personal opinion.

**Comment by brandonweeks** [comment]
This will be resolved in #343. :)

**Comment by jyaworski** [comment]
Yes, apologies for the long time coming. It wasn't a trivial change.

**Comment by mmoll** [comment]
should be fixed by #343, please open a new issue if there are any related problems.
