### ISSUE TITLE
Solaris 10 works

### ISSUE THREAD

**Issue by juaningan** [theforeman/puppet-puppet#293]
Hi, I'm using your module in Solaris 10 and works as expected if you specify package and service names:

My conf:

class {'puppet':
    listen         => false,
    runinterval    => '3600',
    runmode        => 'cron',
    service_name   => 'svc:/network/cswpuppetd:default',
    client_package => 'CSWpuppet3',
    cron_cmd       => '/usr/bin/env /opt/csw/bin/puppet agent --config /etc/puppet/puppet.conf --onetime --no-daemonize',
    show_diff      => true,
  }

**Comment by ekohl** [comment]
Thanks for the information! Do you know if it can run as a service as opposed to cron or isn't that supported? It would also be helpful to have a set of (anonymized) facts since I have close to 0 knowledge of Solaris. I do notice that [rspec-puppet-facts](https://github.com/mcanevet/rspec-puppet-facts) has Solaris 11 facts so maybe we can just test for Solaris and treat 10 and 11 the same.

**Comment by juaningan** [comment]
Yes manage service also works because rely in native service type.

Solaris 10 facter ouput:

architecture => i86pc
augeasversion => 1.3.0
bios_release_date => 04/02/2004
bios_vendor => Intel Corp.
bios_version => 
domain => *******
facterversion => 2.4.1
fqdn => *******
gid => root
hardwareisa => i386
hardwaremodel => i86pc
hostname => *******
id => root
interfaces => lo0,iprb0
ipaddress => *******
ipaddress_iprb0 => *******
ipaddress_lo0 => 127.0.0.1
is_virtual => false
kernel => SunOS
kernelmajversion => Generic_147148-26
kernelrelease => 5.10
kernelversion => Generic_147148-26
macaddress => 00:13:20:3c:6e:ab
macaddress_iprb0 => 00:13:20:3c:6e:ab
manufacturer => 
memoryfree => 256.46 MB
memoryfree_mb => 256.46
memorysize => 511.00 MB
memorysize_mb => 511.00
mtu_iprb0 => 1500
mtu_lo0 => 8232
netmask => 255.255.255.0
netmask_iprb0 => 255.255.255.0
netmask_lo0 => 255.0.0.0
network_iprb0 => *******
network_lo0 => 127.0.0.0
operatingsystem => Solaris
operatingsystemmajrelease => 10
operatingsystemrelease => 10_u11
os => {"name"=>"Solaris", "family"=>"Solaris", "release"=>{"major"=>"10", "full"=>"10_u11"}}
osfamily => Solaris
path => /opt/csw/bin:/usr/sbin:/usr/bin
physicalprocessorcount => 1
processor0 => Intel(r) Pentium(r) 4 CPU 3.00GHz
processor1 => Intel(r) Pentium(r) 4 CPU 3.00GHz
processorcount => 2
processors => {"models"=>["Intel(r) Pentium(r) 4 CPU 3.00GHz", "Intel(r) Pentium(r) 4 CPU 3.00GHz"], "count"=>2, "physicalcount"=>1}
productname => 
ps => ps -ef
puppetversion => 3.7.4
rubyplatform => i386-solaris2.10
rubysitedir => /opt/csw/lib/ruby/site_ruby/2.0.0
rubyversion => 2.0.0
serialnumber => 
sshdsakey => *******
sshfp_dsa => *******
sshfp_rsa => *******
sshrsakey => *******
swapfree => 2.00 GB
swapfree_mb => 2047.99
swapsize => 2.00 GB
swapsize_mb => 2047.99
system_uptime => {"seconds"=>35100, "hours"=>9, "days"=>0, "uptime"=>"9:45 hours"}
timezone => *******
type => 0x2 (unknown)
uniqueid => 0da096a0
uptime => 9:45 hours
uptime_days => 0
uptime_hours => 9
uptime_seconds => 35100
uuid => 8bef3185-b139-11d9-9a80-0013200b4f9e
virtual => physical
zfs_version => 5
zone_global_brand => native
zone_global_id => 0
zone_global_iptype => shared
zone_global_name => global
zone_global_path => /
zone_global_status => running
zone_global_uuid => 
zonename => global
zones => 1
zpool_version => 32

**Comment by mmoll** [comment]
@juaningan it would be super awesome if you could add Solaris support to this module, see #241 for the agent part and #288 for the master part of FreeBSD as examples, I guess the master part does not have that many users, so that would be only a extra chrerry on top.

I'm quite away from Solaris these days... are Solaris/x86 10 and 11 ISOs freely downloadable for testing purposes?

**Comment by mmoll** [comment]
@juaningan ping?

**Comment by mmoll** [comment]
No reaction, closing. We would need a PR with the respective block of settings in params.pp.
