### ISSUE TITLE
passenger module config generation weirdness on Debian Jessie

### ISSUE THREAD

**Issue by olasd** [theforeman/puppet-puppet#295]
Hi,

I'm trying to use your puppet module for my puppetmaster running Debian Jessie (without Foreman), with packages from the repos (puppet 3.7.2).

My puppetlabs-apache module is at version 1.5.0.

When applying this class declaration
```puppet
# Puppet master profile
class profile::puppet::master {
  $puppetmaster = hiera('puppet::master::hostname')

  class { '::puppet':
    server                      => true,
    server_parser               => 'future',
    server_foreman              => false,
    server_environments         => [],
    server_passenger            => true,
    server_storeconfigs_backend => 'active_record',

    runmode                     => 'none',
    pluginsync                  => true,
    puppetmaster                => $puppetmaster,
  }
}
```
the run succeeds, but the file /etc/apache2/mods-available/zpassenger.load contains
```
LoadModule root /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

There seems to be some issue in scoping somewhere between the apache::mod class and the way the puppet module instantiates it.

Thanks for looking into it!
Nicolas

**Comment by ekohl** [comment]
I find this hard to explain because we only ```include apache::mod::passenger``` and pass no parameters. Are you sure there's not some hiera parameter somewhere?

**Comment by mmoll** [comment]
I tried this without hiera on a single host with your exact config and set the master to the host itself in the manifest - everything works as expected, so I'd also recommend to double-check your hiera variables.

**Comment by mmoll** [comment]
@olasd what's the status here? :point_up:

**Comment by mmoll** [comment]
closing
