### ISSUE TITLE
Changing owner

### ISSUE THREAD

**Issue by roidelapluie** [theforeman/puppet-puppet#302]
Notice: /Stage[main]/Puppet::Config/File[/etc/puppetlabs/puppet]/owner: owner changed 'root' to 'puppet'
Notice: /Stage[main]/Puppet::Config/File[/etc/puppetlabs/puppet]/group: group changed 'root' to 'puppet'

With the new AIO package.

Should we do this or keep the package default?

**Comment by ekohl** [comment]
I would prefer to have as little changes as possible, so I think this is something we should fix.

**Comment by mmoll** [comment]
should be fixed with #308 also
