### ISSUE TITLE
Puppet.conf changes with puppet server

### ISSUE THREAD

**Issue by jae2** [theforeman/puppet-puppet#303]
We have a bit of an awkward issue using this module. We run on AWS EC2 and build AMI's with packer. This basically means we run puppet on a temporary box that then takes a machine image. The problem is once we spin up the real machine from this image the agent's puppet.conf still has the hostname of the previous temporary machine as it's value for certname e.g:
``` certname = some_old_temporary_machine ```

When the agent does a run by contacting the puppetserver the value for certname in puppet.conf does not change, even if we manually edit it ourselves and re-run puppet.  However it does change if we do a standalone run on the agent.

Is there any way we could get the puppet agent to reassert the certname value in it's puppet.conf without doing a standalone run at launch time?

**Comment by ekohl** [comment]
I wonder if you leave out the certname variable in the base image if it will work as expected. Since we use a fact for the certname variable, I'd expect puppet to use the proper fallbacks. I can't fully explain why the standalone run differs from an agent run.

**Comment by jae2** [comment]
@ekohl  Thanks that does appear to be an effective workaround. On the packer build I run with a fact temporarily set called $::bootstrap which uses a bootstrap puppet.conf then afterwards we take the correct config when we sync with the puppet server/master.

**Comment by mmoll** [comment]
can this get closed?

**Comment by jae2** [comment]
Sure, it did solve my issue.
