### ISSUE TITLE
"reports" parameter needs to go into [main] section of puppet.conf

### ISSUE THREAD

**Issue by westbywest** [theforeman/puppet-puppet#311]
I was having problems with an instance of puppetserver deployed by theforeman-puppet displaying this error on agent run, when integrated with puppetDB:
```
[puppet-server] Puppet Attempt to assign to a reserved variable name: 'trusted' on node xmaster.vagrant.vm
```
I found the module is placing the "reports" parameter in the [master] section of the puppetserver's puppet.conf, when it appears to belong in the [main] section instead.
https://tickets.puppetlabs.com/browse/PDB-949?focusedCommentId=198934&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-198934

Also, acknowledging Puppet's own docs about this are vague:
https://docs.puppetlabs.com/guides/reporting.html

**Comment by mmoll** [comment]
Somebody[tm] would need to test the behaviour of puppet master 2.7, 3.x and open a PR... ;)

**Comment by westbywest** [comment]
PR coming Very Soon[tm]

**Comment by mmoll** [comment]
:green_heart:
