### ISSUE TITLE
Allow server property to be set

### ISSUE THREAD

**Issue by pcfreak30** [theforeman/puppet-puppet#321]
Currently puppet/puppet::agent does not allow  server in puppet.conf to get set. I don't want  to hard code an ip in /etc/hosts either.

This should be a class parameter. Currently I am forced to use a custom template.

**Comment by domcleal** [comment]
I think the `puppetmaster` parameter will do this.

**Comment by pcfreak30** [comment]
Yea I was looking for server' or similar, couldn't find it it.

Thanks.
