### ISSUE TITLE
Completeness over brevity?

### ISSUE THREAD

**Issue by jyaworski** [theforeman/puppet-puppet#326]
I wanted to enable msgpack as the preferred_serialization_format on puppet agents, so I looked at this module. I didn't see it as a parameter, so I looked further into the template and noticed puppet::agent_additional_settings and master_additional_settings.

I wanted to ask if there was any desire to go the full route and describe all of the configuration settings (completeness) vs some of the most commonly-used ones. I realize that the settings variables accommodate this functionality without having them as class variables, but should we look at implementing more of this?

https://docs.puppetlabs.com/references/stable/configuration.html#configuration-reference

**Comment by ekohl** [comment]
We don't have an official policy about this, but the general idea is that we actively include common parameters, accept PRs for others. We are sceptical about obscure (deprecated) parameters, but if there's a valid use case I think we're open to it.

**Comment by mmoll** [comment]
:+1: what @ekohl says.
@jyaworski can this get closed? :)

**Comment by jyaworski** [comment]
Yes, I just wanted it documented. Thanks all.
