### ISSUE TITLE
Support for centos

### ISSUE THREAD

**Issue by paulbhart** [theforeman/puppet-puppet#331]
I get the feeling (via some experience) that this package isn't fully configured to support centos.  In particular (total hack, don't follow my example) I had to change "puppet-server" to "puppetserver" in a number of places to get puppserver to launch on centos.

If support is envisioned, let me know and I will get more particular about the suggested changes.

**Comment by brandonweeks** [comment]
We have hundreds of CentOS servers using this module. It's *definitely* supported.

**Comment by domcleal** [comment]
You probably need to set `server_implementation` if you want to use the JVM Puppet Server.  The default behaviour is for the older, pre-AIO packages (where `puppet-server` was a subpackage of the `puppet` SRPM).

https://github.com/theforeman/puppet-puppet/blob/master/manifests/server/install.pp#L11

**Comment by mmoll** [comment]
@paulbhart what's the status here?

**Comment by jyaworski** [comment]
@paulbhart I had to follow @domcleal's advice, but this is definitely working with puppetserver.

**Comment by mmoll** [comment]
closing...
