### ISSUE TITLE
PuppetDB workaround

### ISSUE THREAD

**Issue by roidelapluie** [theforeman/puppet-puppet#339]
When using [PuppetDB](https://github.com/puppetlabs/puppetlabs-puppetdb) and this module, the following dependency is needed:

```puppet
Exec['puppet_server_config-generate_ca_cert'] -> Package['puppetdb']
```

Not sure what to do with that.

**Comment by mmoll** [comment]
It's a bit of a cludge, but how about this?
```diff
diff --git a/manifests/server/config.pp b/manifests/server/config.pp
index b826d2f..84cbb99 100644
--- a/manifests/server/config.pp
+++ b/manifests/server/config.pp
@@ -185,6 +185,7 @@ class puppet::server::config inherits puppet::config {
 
   ## PuppetDB
   if $puppet::server_puppetdb_host {
+    Exec['puppet_server_config-generate_ca_cert'] ->
     class { '::puppetdb::master::config':
       puppetdb_server             => $puppet::server_puppetdb_host,
       puppetdb_port               => $puppet::server_puppetdb_port,
```

**Comment by roidelapluie** [comment]
it is not before the config but really before the package. Package postinstall script expects SSL certificates to be present.

**Comment by roidelapluie** [comment]
currently I have added the hack on my internal profile_puppet module.

**Comment by mmoll** [comment]
Hrm, I'm just seeing... As we only manage the server config and not the whole PuppetDB stuff anyway, there's not more we can do here, IMHO.

**Comment by ekohl** [comment]
@roidelapluie looking at the code it should be ```Package[$::puppetdb::puppetdb_package]```.

@mmoll I think we can add the dependency in our module at the place you mentioned.

**Comment by roidelapluie** [comment]
that will only affect puppet masters, not puppetserver setups

**Comment by mmoll** [comment]
I'm a bit unsure what to do here. theforeman-puppet only has the integration to configure a master and thus is using `::puppetdb::master::config` which installs the puppetdb-terminus package. Can we somehow detect if the puppetdb module is also used to set up the PuppetDB server itself?

**Comment by roidelapluie** [comment]
That's why I created this ticket. Maybe just a note in the README is enough.

**Comment by ekohl** [comment]
You could work with ```if defined()``` but that's ugly so a known issue in the README is the best course of action.

**Comment by roidelapluie** [comment]
There is another hack needed:

```
 Class['puppetdb::master::puppetdb_conf'] ~> Class['puppet::server::service']
```

**Comment by mmoll** [comment]
@roidelapluie that one could go into the `if $puppet::server_puppetdb_host {` paragraph or does that touch other things?

**Comment by roidelapluie** [comment]
Well should we assume that people are using puppetlabs-puppetdb to configure their puppetdb?

**Comment by mmoll** [comment]
if `$puppet::server_puppetdb_host` is set, theforeman-puppet uses `puppetdb::master::config` from puppetlabs-puppetdb, which in turn (AFAICT) uses `puppetdb::master::puppetdb_conf` in that case anyway, but please correct me, if I'm wrong. :)

**Comment by roidelapluie** [comment]
Thanks for looking deeper than me, you are right.

**Comment by roidelapluie** [comment]
then what about we also integrate 
```
Exec['puppet_server_config-generate_ca_cert'] -> Package['puppetdb']
```
?

**Comment by mmoll** [comment]
I think that's not possible at the moment, as this module here does _only_ support the configuration of the puppet master side and touches nothing related to the PuppetDB server side. The background of this is that this way setups with a remote PuppetDB are perfectly supported. If a PuppetDB server installation should be managed, that would probably require way more work.

The usecase I had for implementing PuppetDB support back then was exactly that kind of seperated setup.

**Comment by mmoll** [comment]
@roidelapluie could you please open a PR for that later change and add a hint to the documentation for the original issue?

**Comment by mmoll** [comment]
@roidelapluie ping? :point_up:
