### ISSUE TITLE
systemd runmode does not work by default with Puppet 4 AIO

### ISSUE THREAD

**Issue by roidelapluie** [theforeman/puppet-puppet#340]
We use /urs/bin/env for cron and systemd run modes.

Which gives 

```
Dec 16 08:40:01 foo.bar[21958]: /usr/bin/env: puppet: No such file or directory
```

with the AIO package.

**Comment by GregSutcliffe** [comment]
I'm seeing this too - for now I'm overriding with `$systemd_cmd`. The question in my head is, do we try to guess the path to the binary in the default command? Or is that asking for trouble?

**Comment by roidelapluie** [comment]
We could rename $puppetca_path to puppet_path and use that?

**Comment by roidelapluie** [comment]
Or have a bindir here https://github.com/theforeman/puppet-puppet/blob/master/manifests/params.pp#L83

**Comment by GregSutcliffe** [comment]
reusing $puppetca sounds good, I don't think they're every going to be in different directories?

**Comment by roidelapluie** [comment]
we should remove $puppetca_path and add a more generic $puppet_path on next to other directories definitions (on the top of the file).

**Comment by GregSutcliffe** [comment]
+1
