### ISSUE TITLE
wrong permissions on environments.conf

### ISSUE THREAD

**Issue by mleklund** [theforeman/puppet-puppet#349]
When you set puppet::server_environments_group, and or puppet::server_environments_user, envrionments.conf ends up with differing permissions.  This can cause spurrious reloads of puppetmaster or puppetserver.

in my environment I used this to fix it:

```
--- a/modules/puppet/manifests/server/env.pp
+++ b/modules/puppet/manifests/server/env.pp
@@ -38,8 +38,8 @@ define puppet::server::env (
     if $manifest or $config_version or $custom_modulepath or $environment_timeout {
       file { "${basedir}/${name}/environment.conf":
         ensure  => file,
-        owner   => 'root',
-        group   => $::puppet::params::root_group,
+        owner   => $owner,
+        group   => $group,
         mode    => '0644',
         content => template('puppet/server/environment.conf.erb'),
       }
```

though that is probably not right if running with git, though git users may not be messing with the user settings.

Pull request here #350

**Comment by mmoll** [comment]
could you please open a pull request with this change to discuss?

**Comment by mleklund** [comment]
#350
