### ISSUE TITLE
neither main, nor agent receives "confdir" variable

### ISSUE THREAD

**Issue by alathers** [theforeman/puppet-puppet#352]
Several things reference $confdir in [main] and [agent], but the variable is not in any of the templates pushed to either, and is only available in [master]

**Comment by mmoll** [comment]
Not sure if I understand that issue correctly but `$confdir` itself is a Puppet variable, normally pre-filled, try `puppet config print confdir` on your system and you'll get the actual value.

**Comment by mmoll** [comment]
@alathers ping?

**Comment by alathers** [comment]
Apologies.
confdir is an assumed default on the platform, but it doesn't seem to actually ever get enforced.  It *is* supported by the puppet config file however:

$ puppet agent --genconfig | grep confdir
    confdir = /etc/puppet

This would seem meaningful to support, as it allows for both verbosity and consistency, both critical for multi-platform support.

Maybe I'm misunderstanding.  Is the assumption that, prior to applying this module, I should have first dropped a default config in place somehow?

**Comment by mmoll** [comment]
if you open a PR, we can review it, but until now all our supported platforms (quite some Linux variants with native and AIO packages, FreeBSD and MS WIndows) did work flawlessly without having this explicitly set.

If you are having a scenario were you need to change that default, please let us know, or are you experiencing a specific problem in an existing setup?

**Comment by alathers** [comment]
It's mostly just an audit ability and guarantee thing for my needs.  If it's not explicitly set, I can't divine "for sure" that it's set as I expect.

Definitely not an end of the world issue, just trying to work through the hurdles of changing hand deployed configs over to use a module instead.

**Comment by mmoll** [comment]
I see. How about using `$additional_settings` for that?

**Comment by domcleal** [comment]
> confdir is an assumed default on the platform, but it doesn't seem to actually ever get enforced. It is supported by the puppet config file however:
> 
> $ puppet agent --genconfig | grep confdir
> confdir = /etc/puppet

It's indeed a setting, but it makes no sense to set it in the config file as Puppet needs to know the confdir to find the config file in the first place.  I'm not sure what would happen if you changed it in the config file itself.

The value of confdir is defined in the Puppet source code, and sometimes patched by the package distributor.

> This would seem meaningful to support, as it allows for both verbosity and consistency, both critical for multi-platform support.
> 
> Maybe I'm misunderstanding. Is the assumption that, prior to applying this module, I should have first dropped a default config in place somehow?

As it's a built in value, it's up to the package vendor really.

**Comment by alathers** [comment]
It's more for the supportability end in my case.  As it's configurable, it's meaningful for my team to have it actually called out.  It helps the config be self-documenting, rather than instructing a team that, for each supported platform, you need to find an example host and inspect for the relevant config.  It also helps ensure that the config I am trying to enforce *is* the config I'm enforcing.  

fwiw: additional_settings will give me what I need in this case.  thanx @mmoll
