### ISSUE TITLE
autosign file is not created

### ISSUE THREAD

**Issue by szemlyanoy** [theforeman/puppet-puppet#362]
Hi all,

It seems file $confdir/autosign.conf is not created at all which ends up with unsigned cert requests 

I propose simple file resource with template content which just iterates over array of ACLs

Cheers,
Sergey

**Comment by domcleal** [comment]
Yes, this should probably be in this module.

We currently manage it in for Foreman's purposes in another module: https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/puppetca.pp, so we'll need to remove from there.

**Comment by szemlyanoy** [comment]
File resource mentioned above misses few things:
1. content filling from array
2. usage of $autosign value (default is "$confdir/autosign.conf { mode = 664 }")  as file target

**Comment by mmoll** [comment]
@szemlyanoy could you open a PR with your proposed changes? we would be happy to have a look. :)

**Comment by szemlyanoy** [comment]
On it!
Can I get access to collaborators please?

**Comment by mmoll** [comment]
@szemlyanoy, please fork this repo and open a pull request from your fork to this repo, thanks!

**Comment by szemlyanoy** [comment]
Hi all,

build is failed due to warning:
manifests/config.pp:34:WARNING: string containing only a variable

But why is that treated as not appropriate style
 file { "${autosign_target}":   
?

**Comment by domcleal** [comment]
It can simply be written as `file { $autosign_target:`
