### ISSUE TITLE
Upgrade to puppetserver 2.3 fails on EL

### ISSUE THREAD

**Issue by brandonweeks** [theforeman/puppet-puppet#373]
https://docs.puppetlabs.com/puppetserver/2.3/release_notes.html#modifications-to-bootstrapcfg-might-cause-problems-during-upgrades-to-230

We're touching this file in `manifests/server/puppetserver.pp` which triggers this problem. Not sure how to solve this without a facts that we can reference to determine puppetserver version.

**Comment by mmoll** [comment]
are there any other modules for puppetserver that ran into the same problem (and maybe already solved it)?

**Comment by alexjfisher** [comment]
https://github.com/jlambert121/jlambert121-puppet/pull/59 looks like it might be trying to address the same problem?

**Comment by alexjfisher** [comment]
One possible solution (although I'm sure better ones exist!)...

This module uses augeas to modify bootstrap.cfg, so maybe a 'refreshonly' exec refreshed by the package resource but before the augeas resource can replace bootstrap.cfg with bootstrap.cfg.rpmnew (at least for EL platforms).

That more or less matches the suggestion in https://docs.puppetlabs.com/puppetserver/2.3/release_notes.html#modifications-to-bootstrapcfg-might-cause-problems-during-upgrades-to-230

**Comment by mmoll** [comment]
even more ugly but "better" would maybe be an mv exec that's running when there's an .rpmnew file as I can normally just fine do an yum update by hand (or cron) and run puppet after that

**Comment by alexjfisher** [comment]
good point.  What about the other operating systems?

**Comment by alexjfisher** [comment]
I've been wondering if there's anything we can do with the 'unless' attribute of the augeas type?

**Comment by mmoll** [comment]
in Debian it would be .dpkg-dist... handling this without moving files around would be much better, of course.

**Comment by alexjfisher** [comment]
The trapperkeeper lens seems a bit broken.

If I delete
```
puppetlabs.services.ca.certificate-authority-disabled-service/certificate-authority-disabled-service
```
from bootstrap.cfg and rerun puppet, it comes back as
```
puppetlabs.services.ca.certificate-authority-disabled-service:certificate-authority-disabled-service
```
(incorrect separator).

**Comment by mmoll** [comment]
Regarding the lens, please see #343 and camptocamp/puppet-puppetserver#25 for the history. From what I can see (might be wrong) that followup change we have in this module here was never pull-requested to the augeas repo.

**Comment by alexjfisher** [comment]
I did see those posts.  The version in this module *is* the version from the camptocamp module *with* the changes in that PR applied.  I just don't think those changes were quite right somehow. :)
@jyaworski ?

Meanwhile I think adding a puppetserver_version fact is probably going to be necessary (if not now, soon enough).  If the puppetserver isn't yet installed, the fact will be missing and the best we can do is probably to assume a puppetserver_version based on the version of puppet.  Is having to run puppet twice a big deal?

(I wish there was a way of aborting and restarting a puppet run so that new facts would be available.)

**Comment by mmoll** [comment]
it is a very big deal, especially for foreman-installer, I really don't see that working... We should design the module for now without having such a fact and with overridable defaults. It's probably going to be hard when puppetserver2 is such a moving target...

**Comment by alexjfisher** [comment]
I can come up with a PR, but want to know how bootstrap.cfg should be managed.

1. Use the trapperkeeper lens (but someone other than me would have to fix it first)
2. Use the Simplelines lens (which is what the [camptocamp module does for bootstrap.cfg](https://github.com/camptocamp/puppet-puppetserver/blob/master/manifests/config/bootstrap.pp#L29))
3. Use a simple erb template.

I propose adding a puppetserver_version parameter with a default of 2.3.  The default will periodically be updated to the latest available version as required.

**Comment by mmoll** [comment]
maybe I'm seeing this wrong, but is the trapperkeeper lens really used for that one and only file?

**Comment by jyaworski** [comment]
Yes, it's only used for bootstrap.cfg at this time. I _suspect_ they will add more files in that format, but I can't be certain.

**Comment by mmoll** [comment]
I really don't see any great options at the moment.

Best would be if the trapperkeeper lens gets fixed upstream to work for all intended use cases... Otherwise 3 might even be a better than 2.

Also I'm really reluctant to have that version parameter, but probably it'll be needed in the future.

**Comment by mmoll** [comment]
Please see mmoll/puppet-puppet/#@430fedc, however, that doesn't seem to work: https://travis-ci.org/mmoll/puppet-puppet/builds/122836149

**Comment by mmoll** [comment]
Interestingly it seems to work like that: mmoll/puppet-puppet@854d98d

**Comment by alexjfisher** [comment]
@mmoll Interesting that it works with an intermediate $ps_23 variable, or now that you're comparing the right version number?

**Comment by mmoll** [comment]
that it works with an intermediate variable...

**Comment by alexjfisher** [comment]
@mmoll Actually, I think I've come across this before.  The limitation doesn't exist in puppet 4, but in version 3 (at least when not using future parser)...

> [Control variables in selectors must be variables or functions that return values. You cannot use expressions as control variables.](https://docs.puppet.com/puppet/3.7/reference/lang_conditional.html#control-variables)

**Comment by alexjfisher** [comment]
So, you could use ```versioncmp``` by itself as the control variable and use -1,0,1 as cases, but you can't use ```versioncmp(a,b) >=0``` as the control variable and true/false as cases.
