### ISSUE TITLE
/etc/sysconfig/puppet is out of module control 

### ISSUE THREAD

**Issue by szemlyanoy** [theforeman/puppet-puppet#386]
Hey all,

Is it only my who stumbled upon absence of any control under mentioned config by puppet-puppet module? I want to change log file for agent while amending of this config is the only way to approach it.

Comments please?

Regards,
Sergey

**Comment by brandonweeks** [comment]
#387 touches on the same issue.

**Comment by szemlyanoy** [comment]
seems this config is partially maintained in puppet::server::puppetserver  but only for puppetserver and only limited by java

**Comment by alexjfisher** [comment]
and in https://github.com/theforeman/puppet-puppet/issues/387 it's because the java args have been modified, that the upgrade of the RPM doesn't replace the file with the new version.

**Comment by mmoll** [comment]
At the risk of coming across as the grumpy, old man: pull requests welcome.

From my experience in the last years, especially given that this module supports a lot of package types, versions and combinations of puppet and puppetserver, this task will be _really_ tedious.

**Comment by ekohl** [comment]
This file is now optional (`puppet-agent-6.4.0-1stretch`):
```
$ grep EnvironmentFile /lib/systemd/system/puppet.service
EnvironmentFile=-/etc/sysconfig/puppetagent
EnvironmentFile=-/etc/sysconfig/puppet
EnvironmentFile=-/etc/default/puppet
```

The default content doesn't have a lot of options:
```
$ cat /etc/default/puppet 
# You may specify parameters to the puppet client here
#PUPPET_EXTRA_OPTS=--waitforcert=500
```

The recommended way is using drop ins. From the service file:
```
 Local settings can be configured without being overwritten by package upgrades, for example
# if you want to increase puppet open-files-limit to 10000,
# you need to increase systemd's LimitNOFILE setting, so create a file named
# "/etc/systemd/system/puppet.service.d/limits.conf" containing:
# [Service]
# LimitNOFILE=10000
# You can confirm it worked by running systemctl daemon-reload
# then running systemctl show puppet | grep LimitNOFILE
```

That means you can also use `systemd::dropin` on most platforms. I'm closing this issue, but we'll still merge a PR that would address the issue.
