### ISSUE TITLE
Upgrade to Puppetserver 2.x from 1.x fails on EL

### ISSUE THREAD

**Issue by alexjfisher** [theforeman/puppet-puppet#387]
This module manages the JAVA_ARGS in `/etc/sysconfig/puppetserver`
As a result, when the RPM is upgraded to version 2, `/etc/sysconfig/puppetserver` is not overwritten with the package's new version.
`INSTALL_DIR`, `CONFIG` and `BOOTSTRAP_CONFIG` all end up being wrong and the puppetserver service can't start.

**Comment by brandonweeks** [comment]
I ran into this as well.

**Comment by mmoll** [comment]
As Puppetserver <2 got desupported by this module, this won't be solved, sorry...

**Comment by alexjfisher** [comment]
@mmoll No worries.  I've long since upgraded. :)
