### ISSUE TITLE
server_ca_proxy doesn't work with http vhost.

### ISSUE THREAD

**Issue by falencastro** [theforeman/puppet-puppet#396]
Hi,

Currently redirection from the http vhost to a https ca, through server_ca_proxy, doesn't work, as SSLProxyEngine On, is not being set.

Workaround is setting ssl_proxyengine on manifests/server/passenger.pp

```puppet
apache::vhost { 'puppet-http':

      docroot         => "${app_root}/public/",
      directories     => $directories_http,
      port            => $http_port,
      ssl_proxyengine => $ssl_proxyengine, # <------
      custom_fragment => join([
          $custom_fragment ? {
            undef   => '',
            default => $custom_fragment
          },
          'SetEnvIf X-Client-Verify "(.*)" SSL_CLIENT_VERIFY=$1',
          'SetEnvIf X-SSL-Client-DN "(.*)" SSL_CLIENT_S_DN=$1',
        ], "\n"),
      options         => ['None'],
      require         => Class['::puppet::server::rack'],
    }
```

**Comment by mmoll** [comment]
Could you get a bit more into detail in what configurations this problem does occour and/or open a pull request with the changes for discussion?

**Comment by falencastro** [comment]
Sure, a little more context: My F5 LoadBalancers are offloading SSL in front of my puppetmasters which are running on plain http on port 8139 (server_http => true). 

On the other hand my CA server is still running on just https/8140, so when I set server_ca_proxy to a https address, I end up with an internal server error, and apache complains on logs ([Wed May 11 19:23:48.251305 2016] [ssl:error] [pid 25742] [remote 172.xx.xxx.xx:8140] AH01961: SSL Proxy requested for default:80 but not enabled [Hint: SSLProxyEngine]).

So with the ssl_proxyengine => $ssl_proxyengine line also on the http vhost, apache is able to forward http->https properly.

I'll see about the pull request.
