### ISSUE TITLE
Duplicate resource declaration if user drops their own autosign script/file

### ISSUE THREAD

**Issue by nick-george** [theforeman/puppet-puppet#413]
I have been deploying my own autosign.sh file via puppet, however, with version 5.0.0 of this module, that is no longer possible because of the code at manifests/server/config.pp:115. 

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: File[/etc/puppet/autosign.sh] is already declared`

An easy fix is to allow the user to supply the content of the autosign.sh, or don't try to set the mode of the file within this module.

**Comment by mmoll** [comment]
This is fallout of #381 and also touches #370. Would you be willing to flesh out out a pull request for this (just being able to provide the content/source based on some parameter is set to undef or not, or similar. #370 itself wouldn't be needed)?
