### ISSUE TITLE
support http configuration for puppetserver

### ISSUE THREAD

**Issue by mmoll** [theforeman/puppet-puppet#429]
This module does support HTTP setups with passenger (`$server_http` and so on...), but setting any of these won't result in a similar config for puppetserver.

Further docs:
https://docs.puppet.com/puppetserver/latest/config_file_webserver.html
https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/blob/master/doc/jetty-config.md

**Comment by mmoll** [comment]
for reference: #253

**Comment by superfantasticawesome** [comment]
PR #438 sets up puppetserver to listen as a backend service using the directives from PR #253 and includes CA-verified TLS on the frontend apache instance. It is configured according to this document from Puppet Labs: https://docs.puppet.com/puppetserver/latest/external_ssl_termination.html
