### ISSUE TITLE
Atomic changes with (puppetserver) auth.conf using puppetlabs-puppet_authorization

### ISSUE THREAD

**Issue by superfantasticawesome** [theforeman/puppet-puppet#439]
Currently, the content of auth.conf is supplied via template. This prevents atomic changes to authorization rules, thus prohibiting customizations to server roles.

By implementing [this module](https://github.com/puppetlabs/puppetlabs-puppet_authorization), authorization rules could be added in a more granular fashion, thus giving users access to all authorization rules for more customized deployments of puppetserver.

See this [sample code](https://github.com/superfantasticawesome/puppet-puppet/blob/authorization/manifests/server/authorization.pp) for reference.

**Comment by superfantasticawesome** [comment]
PS: The sample code as is does not expose any parameters, nor has a model been developed to allow user customizations the authorization rules. The sample code merely rewrites the existing erb template in code that the puppet_authorization module could parse and apply as a catalog.

**Comment by mmoll** [comment]
As said in #438, pulling in a new module is OK, but the existing auth.conf rules and version dependent changes need to get transplanted and backed by spec tests.

**Comment by superfantasticawesome** [comment]
@mmoll The puppet_authorization module includes its own battery of spec tests; however, the only tests I can see that are relevant to authorization in the current spec tests are that auth.conf exists and contains version specific lines. Truth be told, I couldn't write a spec test with a gun to my head... but I have added the existing rules and version-specific configurations in this [forked repo](https://github.com/superfantasticawesome/puppet-puppet/blob/authorization/manifests/server/authorization.pp).

Regarding any additional required tests, I would most definitely need some help writing them... but currently the code works as is... and delivers an auth.conf file that filters just as the existing one.

What I'm noodling over now is the use case mentioned in #438 where a loadbalancer is terminating SSL... and determining which resources will need array variables for the allow parameter. I was looking at the legacy auth.conf for examples and was thinking that the "auth_allowed" array could be used for this purpose. Thanks.

**Comment by ekohl** [comment]
I agree that using that module is a good idea because the template shouldn't be this complex. What you can also do is have multiple presets of auth settings. So maybe ```auth/base```, ```auth/standalone``` and ```auth/loadbalanced```. All depending on how big the various if blocks become.

**Comment by superfantasticawesome** [comment]
The logic for each use case that you've described (base, standalone and loadbalancer) already exists in combintation with the code I provided in this [link](https://github.com/superfantasticawesome/puppet-puppet/blob/authorization/manifests/server/authorization.pp) and existing module parameters. I think that's the best way to build the authorization file; e.g., from a subclass, rather than a template.

I have not yet tested the code with a loadbalancer but will do that with an external apache instance soon. One key difference that I notice between the passenger vhost and the catalog vhost I developed is that the ProxyPreserveHost directive is enabled in my in my initial PR. Beyond that, it's apples to apples, minus the passenger config.

I'm currently developing the reverseproxy subclass in another branch and will post back here with a link to it shortly.

**Comment by mmoll** [comment]
I played around with this today and found out that puppetlabs-puppet_authorization is puppet 4+ only, so I don't think that's really an option for us. The underlying puppetlabs-hocon would still be 3+ compatible.

**Comment by superfantasticawesome** [comment]
Ok, thanks... that's important note... and it would be considerable work to port the rules via the hocon module. Would it be worth employing a conditional statement, based on version, or is that too elaborate?

**Comment by mmoll** [comment]
Maybe it's also an option to migrate that auth.conf to concat fragments? But I'm really unsure what's the best way to handle that...

**Comment by mmoll** [comment]
I tried to contain the puppet_authorization code to 4.x Puppet versions, but didn't succeed. So I'm leaning towards closing this issue, as we won't drop Puppet 3.x compatibility any time soon.

**Comment by mmoll** [comment]
closing.
