### ISSUE TITLE
Reserved variable name collision using "server_facts"

### ISSUE THREAD

**Issue by reubenavery** [theforeman/puppet-puppet#463]
When Trusted Server Facts are enabled, the assignment of $server_facts in params.pp:343 results in error.

This variable needs to be renamed to something ala $foreman_server_facts.

See: https://docs.puppet.com/puppet/latest/lang_facts_and_builtin_vars.html#serverfacts-variable

**Comment by reubenavery** [comment]
i see this has already been fixed on master.  Lots of other changes queued up vs 6.0.1 tag.  can we expect a release soon?

**Comment by mmoll** [comment]
@reubenavery yes, soonish, together with the foreman-installer 1.14 branching

**Comment by domcleal** [comment]
7.0.0 is now available on the Forge with this fix.
