### ISSUE TITLE
Non existent facts / top scope vars on Puppet 4.x

### ISSUE THREAD

**Issue by james-powis** [theforeman/puppet-puppet#465]
2016-12-07 13:22:12,464 WARN  [qtp1376229403-70] [puppetserver] Puppet Unknown variable: '::domain'. at /etc/puppetlabs/code/environments/production/modules/puppet/manifests/params.pp:37:26
2016-12-07 13:22:12,471 WARN  [qtp1376229403-70] [puppetserver] Puppet Unknown variable: '::puppetmaster'. at /etc/puppetlabs/code/environments/production/modules/puppet/manifests/params.pp:179:32

The domain and puppetmaster facts are non existent, where are these supposed to be sourced from?

**Comment by ekohl** [comment]
Are you running masterless by any chance? I also noticed the domain one wasn't present in some rspec-puppet-facts version so there may have been some chance in facter as well. Could you show the versions of puppet, facter along with your OS? I'm also interested in output of ```hostname``` and ```hostname -f``` to see if they include a domain.

**Comment by james-powis** [comment]
```logs
[root@88662-docker01 ~]# puppet --version
4.5.2
[root@88662-docker01 ~]# facter --version
3.2.0 (commit 148948d795fbdcf6bcf51ed36a73f496775835dc)
[root@88662-docker01 ~]# facter domain

[root@88662-docker01 ~]# hostname
88662-docker01
[root@88662-docker01 ~]# hostname -f
88662-docker01
[root@88662-docker01 ~]# 
```

and to describe why we don't have the domain set is largely because of multi tenancy and hostname conventions of near folklore times... however with strict variables coming I think the appropriate path is check for key existence in $facts and evaluate if undef / null or something like pick($::domain, undef)

**Comment by james-powis** [comment]
and sorry no this is Masterfull Runs

**Comment by ekohl** [comment]
That confirms my suspicions. Would you be able to come up with a PR for this?

**Comment by james-powis** [comment]
Sure no problem

**Comment by alexjfisher** [comment]
@james-powis Rather annoyingly, the `$facts` hash isn't available by default on puppet 3.

Instead, you could use the `defined` function, but that doesn't work properly on puppet < 3.7.5.
Or you can use `getvar('::some_fact')` but that's broken on recent puppet 4 unless stdlib >= 4.13.0

**Comment by james-powis** [comment]
https://libbylayla1984.files.wordpress.com/2014/01/8ffd8b1e292d97550b50da36ed9c1068261ac8dcdf3fb7445755f7418401d30f.jpg

**Comment by ekohl** [comment]
Looking at https://github.com/theforeman/puppet-puppet/blob/3e90793358901dd93f218ec762977a1d79710aa6/manifests/params.pp#L201-L208 I'd expect this to be covered already. This was added after 6.0.0 but is available in the freshly released 7.0.0.

Maybe this logic needs to be applied to ```$::domain``` as well?

**Comment by james-powis** [comment]
unfortunately defined( ) where the variable is undefined throws a soft error on 4.x

**Comment by james-powis** [comment]
SO I am making considerable progress in identifying what needs to occur... however I cannot for the life of me identify where the hell $::puppetmaster is coming from... Its not a fact, its not a custom_fact, its not a server side variable, it is absolutely nothing... any one got any insight?

**Comment by alexjfisher** [comment]
> On 10 Dec 2016, at 23:57, James Powis <notifications@github.com> wrote:
> 
> SO I am making considerable progress in identifying what needs to occur... however I cannot for the life of me identify where the hell $::puppetmaster is coming from... Its not a fact, its not a custom_fact, its not a server side variable, it is absolutely nothing... any one got any insight?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
The foreman ENC sets a top scope 'puppetmaster' variable.

**Comment by james-powis** [comment]
@alexjfisher Thanks for the clarification, unfortunately that basically means there is no way to codify our way into not generating a log entry that $::puppetmaster is not present... However the PR linked is functional for domain...

**Comment by mmoll** [comment]
first part done in #467

**Comment by mmoll** [comment]
#461 is also in now.
What's the current status?

**Comment by james-powis** [comment]
I think we are done
