### ISSUE TITLE
Unable to update jvm JAVA_ARGS from foreman-installer

### ISSUE THREAD

**Issue by dekimsey** [theforeman/puppet-puppet#471]
When I attempted to upgrade to Puppet 4 (as part of Katello 3.2) on EL7, I ran into the known [java noexec tmpdir][1] issue. However, since foreman-installer owns the `/etc/syconfig/puppetserver` file. I am unable to persist changes to the `JAVA_ARGS` value. (Or if I can, I don't know how to do so. Nothing in scenarios.d stands out to me as a possible setting.)

In short, I need to be able to configure the [params.pp#L416][2], `$server_jvm_extra_args`.

[1]: https://docs.puppet.com/puppetserver/latest/known_issues.html#tmp-directory-mounted-noexec
[2]: https://github.com/theforeman/puppet-puppet/blob/master/manifests/params.pp#L416

**Comment by stbenjam** [comment]
Hi,

Thanks for the bug report - but this doesn't belong here. The puppet module supports this feature, `$server_jvm_extra_args` is a parameter on the puppet class.  It's just not currently exposed to users via an installer parameter.

It is already planned to be exposed in 3.3, under http://projects.theforeman.org/issues/17714. You would be able to pass `--puppet-server_jvm_extra_args` to change it in 3.3.

A workaround may be to edit the params.pp on your Katello server as a temporary workaround on 3.2. It's in /usr/share/katello-installer-base.

If you need more info please follow the [support process here](https://theforeman.org/support.html), or if you find a bug report it in the Katello bug tracker http://projects.theforeman.org/projects/katello/issues/new

**Comment by dekimsey** [comment]
Ah, I didn't see the foreman issue. Thanks @stbenjam.
