### ISSUE TITLE
Specifying puppetserver version a bit confusing.

### ISSUE THREAD

**Issue by claflico** [theforeman/puppet-puppet#472]
Trying to migrate an existing puppet setup from using jlamber121 module to this module so that I can upgrade versions. Am currently running the following versions on CentOS 7:

puppetlabs-release-pc1-1.0.0-2.el7.noarch
puppet-agent-1.4.2-1.el7.x86_64
puppetexplorer-2.0.0-1.noarch
puppetdb-4.0.2-1.el7.noarch
puppetserver-2.3.2-1.el7.noarch
puppetdb-termini-4.0.2-1.el7.noarch

Trying to specify via hiera: 
puppet::version: '1.4.2'
puppet:server_puppetserver_version: '2.3.2'

results in puppet trying to install 
/bin/yum -d 0 -e 0 -y downgrade puppetserver-1.4.2

After digging into the manifests and testing different variables I found that I have to specify it twice to get everything to work properly:
puppet::server_puppetserver_version: '2.3.2'
puppet::server_version: '2.3.2'

**Comment by mmoll** [comment]
This is, IMHO, a documentation issue and really a problem. As most people just use the latest version of Puppet/Puppetserver it's not often visible. The thing is that version and server_version are package (RPM/DEB) version, while server_puppetserver_version is the application version of Puppetserver to generate the configs correctly for the specific version.

**Comment by preisbeck** [comment]
Just stumbled over this myself. After working with the module myself for several weeks now, I never noticed the second version declaration.

**Comment by mmoll** [comment]
It can't be done in the module, as e.g. Debian and FreeBSD do have subversions in their packaging.

**Comment by ekohl** [comment]
I'm not sure how to proceed with this. Should we extend the README a bit?
