### ISSUE TITLE
Puppet & puppetserver versions don't conform to Major.Minor.Patch in CentOS7

### ISSUE THREAD

**Issue by claflico** [theforeman/puppet-puppet#473]
This module verifies that versions are in Major.Minor.Patch format but in CentOS 7 the packages don't conform to that so it is constantly trying to install a different version:

puppet-agent-1.4.2-1.el7.x86_64
puppetserver-2.3.2-1.el7.noarch

Notice: /Stage[main]/Puppet::Agent::Install/Package[puppet-agent]/ensure: ensure changed '1.4.2-1.el7' to '1.4.2'
Notice: /Stage[main]/Puppet::Server::Install/Package[puppetserver]/ensure: ensure changed '2.3.2-1.el7' to '2.3.2'

**Comment by claflico** [comment]
This may actually be more related to the confusion from #472. It looks like puppet::server_version & puppet::version are ok with the additional '-1.el7':

puppet::server_version: '2.3.2-1.el7'
puppet::version: '1.4.2-1.el7'

It's only puppet::server_puppetserver_version that doesn't like it because 

puppet::server_puppetserver_version: '2.3.2'

works but 

puppet::server_puppetserver_version: '2.3.2-1.el7'

gives 

Error while evaluating a Function Call, validate_re(): "2.3.2-1.el7" does not match "^[\\d]\\.[\\d]+\\.[\\d]+$" at /etc/puppetlabs/code/environments/test/modules/puppet/manifests/server.pp:530:5

**Comment by mmoll** [comment]
it is 100% related to #472, commenting there.
