### ISSUE TITLE
PassengerRoot does not get set in apache

### ISSUE THREAD

**Issue by treyormsbee** [theforeman/puppet-puppet#489]
I think this is either a bug or I am missing something.  I cannot get puppet server to deploy with apache/passenger.  Everything gets set perfect except PassengerRoot is not set anywhere.  

In server/passenger.pp  I see no entry for PassengerRoot,  and it does not appear to get set with ::apache::mod::passenger.

Where is this supposed to be set at?  or Is it missing?

**Comment by treyormsbee** [comment]
After a bit more of digging, PassengerRoot should be set within ::apache::mod::passenger.  passenger.pp just includes and it does not appear there is a default location in the module (probably used to be).  I can make the change if needed;  but I only have the default locations for Centos if someone gets me the rest of the supported os locations ill edit and submit a pull request.

**Comment by mmoll** [comment]
The defaults come from puppetlabs-apache's params.pp, normally nothing needs to be added. Which OS and OS version are you on? Which Puppet version? Which type of packages (AIO from the PuppetLabs PC1 repo, non-AIO from the Puppetlabs repo, native OS packages)?

**Comment by treyormsbee** [comment]
Centos 7.3, im using puppet 3.8.7 from the non-aio (the old) repos. 

puppet modules list
├── puppetlabs-apache (v1.11.0)
├── puppetlabs-apt (v2.3.0)
├── puppetlabs-concat (v1.1.2)
├── puppetlabs-firewall (v1.8.1)
├── puppetlabs-motd (v1.0.1)
├── puppetlabs-mysql (v3.10.0)
├── puppetlabs-postgresql (v4.9.0)
├── puppetlabs-stdlib (v4.15.0)
├── puppetlabs-xinetd (v2.0.0)
├── theforeman-dhcp (v3.0.0)
├── theforeman-dns (v4.0.0)
├── theforeman-foreman (v7.1.0)
├── theforeman-foreman_proxy (v5.0.0)
├── theforeman-puppet (v7.0.1)
├── theforeman-tftp (v2.0.0)

**Comment by mmoll** [comment]
this seems to work just fine for me:

```
[root@dave-neuweg ~]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
[root@dave-neuweg ~]# puppet module list --modulepath=puppet/modules/
/root/puppet/modules
├── puppet-extlib (v1.1.0)
├── puppetlabs-apache (v1.11.0)
├── puppetlabs-concat (v2.2.0)
├── puppetlabs-stdlib (v4.15.0)
└── theforeman-puppet (v7.0.1)
[root@dave-neuweg ~]# cat puppet/doit.pp 
class { '::puppet':
  server                => true,
  server_foreman        => false,
  server_reports        => 'store',
  server_external_nodes => '',
  puppetmaster          => 'dave-neuweg.kvedulv.de',
}
[root@dave-neuweg ~]# head -n 6 /etc/httpd/conf.d/passenger.conf 
### Begin automatically installed Phusion Passenger config snippet ###
<IfModule mod_passenger.c>
   PassengerRoot /usr/share/ruby/vendor_ruby/phusion_passenger/locations.ini
   PassengerRuby /usr/bin/ruby
   PassengerInstanceRegistryDir /var/run/passenger-instreg
</IfModule>
```

**Comment by treyormsbee** [comment]
Ok,  I see my problem now.   That file is not managed and is only created on first run.  I had removed all the /etc/puppet/* files and /etc/httpd/* to retest my manifests for some reason or another (i dont recall the issue i had) but subsequent puppet runs do not create that file only the initial run.

That file appears to be put in place by the mod_passenger rpm, from the passenger repo.  So,  should it be managed or just installed by the package? I personally think it should be managed, and that could be taken care of by defining passenger_root when applying the ::apache::mod::passenger class.

Let me know what you think.

**Comment by mmoll** [comment]
@treyormsbee Ah, I see, the situation is not how I thought... and different on RH based OSes as opposed to Debian based (where the needed parameters come from puppetlabs-apache's params.pp). Regardless of that I think this needs to get handled in puppetlabs-apache and not theforeman-puppet.

**Comment by domcleal** [comment]
Indeed, this is puppetlabs-apache behaviour, not this module.

The file is deliberately left to the package because there is a large variety of Passenger packages available on various OSes and from various sources requiring different configurations. The setting is specific to how the module is packaged, rather than being specific to an operating system etc. (https://github.com/puppetlabs/puppetlabs-apache/commit/005bf615c96254f74cb2fd53207922ee50abcb2a)

**Comment by treyormsbee** [comment]
Thanks for looking into this!
