### ISSUE TITLE
Default instance/memory values can create unstable configurations with many processors

### ISSUE THREAD

**Issue by kasimon** [theforeman/puppet-puppet#571]
The default instance number/memory configuration for servers with more than 2GB memory

https://github.com/theforeman/puppet-puppet/blob/6735410e6346b616c7875e23af7638b8d6a9c01f/manifests/params.pp#L411

can result in unsuitable configurations for servers with more than 4 processors. According to the [official tuning guide](https://puppet.com/docs/puppetserver/5.1/tuning_guide.html), each server instance should have 512MB memory available. Since the java memory is limited by default at 2GB, but the number of instances unconditionally equals the number of processors, the puppetserver process will run with not enough memory and may quit working at load peaks.

My suggestions would be:
* Either limit instances too: `default_instances =  min(number_processors, 4)`
* or calculate possible instances from number of processors and available memory: `default_instances = min (number_processors, (memory_in_mb / 512) -1)`
* or at least log a warning when more than instances will be configured than fitting into the configured memory

**Comment by ekohl** [comment]
> Either limit instances too: default_instances = min(number_processors, 4)

https://github.com/theforeman/puppet-katello/blob/986a17ea3007f7e5c6ff7c8e9fdb74bef55507c6/manifests/params.pp#L32 implements a similar change and I'd accept a patch that implements this. We don't implement real automatic tuning anyway.
