### ISSUE TITLE
Add a "Managed by Puppet" header to configuration files

### ISSUE THREAD

**Issue by mauricemeyer** [theforeman/puppet-puppet#594]
Hello everyone,

I was wondering why there is no "managed by puppet" header in configuration files. We use e.g.

```
#
# WARNING: This file is auto-generated by puppet!
# WARNING: To change it, edit the file in [wherever the file/template is]
#
```

I suggest adding such a header to all configuration files to clarify that Puppet is in fact managed by Puppet.

**Comment by mmoll** [comment]
@mauricemeyer Personally I find these headers not helpful, but if you want to have it, please open a PR.
