### ISSUE TITLE
forge version missmatch

### ISSUE THREAD

**Issue by TheMeier** [theforeman/puppet-puppet#604]
Puppetforge has https://forge.puppet.com/theforeman/puppet version 9.0.3. I can't find that version at https://github.com/theforeman/puppet-puppet/releases

Also why is 9.0.4 not pushed to the forge?

**Comment by mmoll** [comment]
blacksmith problem... 9.0.3 is 9.0.4 content-wise, I'll fix this over the weekend

**Comment by mmoll** [comment]
should be fine now.
