### ISSUE TITLE
puppet_ca_proxy doesn't pass a valid client cert to upstream ca

### ISSUE THREAD

**Issue by gonoph** [theforeman/puppet-puppet#611]
When puppet_ca_proxy is defined, apache issues this error message when trying to utilize proxy:

```log
Proxy client certificate callback: (:8140) downstream server wanted client certificate but none are configured
```

Recommended changes to [passenger.pp](/theforeman/puppet-puppet/tree/master/manifests/server/passenger.pp) :
1. create `/path/to/combined.pem` from `$ssl_cert` and `$ssl_cert_key`
2. add `SSLProxyMachineCertificateFile /path/to/combined.pem`after `ProxyPassMatch` as custom fragment.

**Comment by bkearney** [comment]
@gonoph is this tied to an upstream issue? Ping @tbrisker for visibility on answer.

**Comment by mmoll** [comment]
@gonoph would you open a PR to the 10.1-stable branch? Otherwise I'd close this one due to GH-650

**Comment by mmoll** [comment]
closing...
