### ISSUE TITLE
ca_proxy pattern does not match

### ISSUE THREAD

**Issue by dlucredativ** [theforeman/puppet-puppet#646]
According to [1], the initial certificate request is via /puppet-ca/v1/certificate/. This does not match the ProxyPassMatch in server/passenger.pp

[1] https://puppet.com/docs/puppet/4.8/http_api/http_certificate.html

**Comment by ekohl** [comment]
We didn't officially deprecate it in this module, but since the passenger support it deprecated in Puppet I consider it deprecated in this module. Actually I'm preparing a PR that removes passenger support altogether.

**Comment by ekohl** [comment]
Closing since https://github.com/theforeman/puppet-puppet/pull/650 is open.
