### ISSUE TITLE
Make max open files configurable for puppetserver

### ISSUE THREAD

**Issue by baurmatt** [theforeman/puppet-puppet#670]
Larger setups tend to use more file descriptors as the default configuration of the OS.

Puppet itself suggest to increase them if needed --> https://puppet.com/docs/pe/2017.3/config_ulimit.html

As we currently do not manage the init script (and I definitely like to keep it that way) the best way is probably to just use the `$config` file for it.

Will send a PR soon :)

**Comment by baurmatt** [comment]
Hmm ok, so just putting `ulimit -n $number` in `$config` isn't working for systemd systems :(

**Comment by alexjfisher** [comment]
I bumped into this today, (about 12 hours after enabling environment caching), so thanks for the PR!
