### ISSUE TITLE
Debian 9: puppetmaster not puppetserver

### ISSUE THREAD

**Issue by spengilley** [theforeman/puppet-puppet#672]
Hi there,

I am attempting to install puppetmaster onto Debian 9 Stretch, using this module.

I have the following parameters set

server => true,
server_package => 'puppetmaster',
server_version => '4.8.2-5'

This does install puppetmaster correctly. However the module attempts to manage the 'puppet' service as well and this is hard-coded to puppetserver which fails of course.

Could the service_name default to ;puppetserver' but be parameterised? I am happy to create a pull request for this simple change but want to check the thinking behind how it currently works first

**Comment by mmoll** [comment]
@spengilley Are you using the 10.1.x release of this module? 11.x removed support for the rack based puppetmaster.

**Comment by spengilley** [comment]
Hi there,

Yes you are correct. Switching to version 10.0 correctly installs puppet-master.

If I use version 11 and remove server_package and server_version but leave server => true I would expect it then to install puppetserver. It actually produces an error that apt cannot find the package puppetserver

**Comment by ekohl** [comment]
That's because Debian doesn't actually have the puppetserver package. You must use the Puppet repositories.

**Comment by ekohl** [comment]
How should we deal with this? Would a message in README be sufficient?
