### ISSUE TITLE
11.0.0 Changelog missing breaking extlib upgrade

### ISSUE THREAD

**Issue by mauricemeyer** [theforeman/puppet-puppet#673]
The 11.0.0 changelog lists the extlib changes as enhancement, but due to the higher version of extlib now required, this is a breaking change.

I’ll add a PR for this tomorrow.

**Comment by ekohl** [comment]
So you consider https://github.com/theforeman/puppet-puppet/pull/639 a breaking change? Not entirely sure what semver says about minimal version dependencies.

**Comment by mauricemeyer** [comment]
On a quick scan, I didn’t find anything about how to deal with dependencies, however #639 broke compatibility with extlib < 3.0.0.

Personally, I’d consider this a breaking change and would deal with those „dependency breaking changes“ as with an API breaking change.

I’ll also read through this thoroughly in semver tomorrow.

**Comment by ekohl** [comment]
Did you find anything? I can change the changelog but wondering what the best practices are here.

**Comment by mauricemeyer** [comment]
I did not find anything in regards to this in semver, but I would consider it a breaking change as it will break for some systems that were supported before.

**Comment by ekohl** [comment]
This was fixed in the 11.0.1 changelog.
