### ISSUE TITLE
Missing dependencies module

### ISSUE THREAD

**Issue by hdep** [theforeman/puppet-puppet#674]
Hi,

this module is missing dependencies for https://forge.puppet.com/puppetlabs/hocon and https://forge.puppet.com/puppetlabs/puppet_authorization module.
This is needed when  $server = true

**Comment by mmoll** [comment]
@hdep in 10.x, the dependency shouldbe correctly specified, while for 11.x, it was refactored away. Whioch errors are you seeing, which version of this module are you using and how did you install it?

**Comment by mmoll** [comment]
@hdep Not 100% sure, but I think with r10k (opposed to librarian-puppet) you need to specify the dependencies also in the Puppetfile. https://forge.puppet.com/theforeman/puppet/9.1.0/dependencies clearly shows that the module itself does have all needed dependencies in its metadata.

**Comment by hdep** [comment]
Ok I understood now that dependencies change between version. I looked at the github master branch so I was misleading. Sorry about the noise !
