### ISSUE TITLE
Manage environment

### ISSUE THREAD

**Issue by hdep** [theforeman/puppet-puppet#675]
Hi,

On my puppet master, the module still trying to create development environment. The issue is I use r10k so it cleans up the folder  /etc/puppetlabs/code/environments/ each minutes, then puppet deploy the folder development and restart my puppet master.

I don't find the way to tell the module to not create this environment ? 

```
Notice: /Stage[main]/Puppet::Server::Config/File[/etc/puppetlabs/code/environments/common]/ensure: created
Notice: /Stage[main]/Puppet::Server::Config/Puppet::Server::Env[development]/File[/etc/puppetlabs/code/environments/development]/ensure: created
Notice: /Stage[main]/Puppet::Server::Config/Puppet::Server::Env[development]/File[/etc/puppetlabs/code/environments/development/modules]/ensure: created
Notice: /Stage[main]/Puppet::Server::Config/Puppet::Server::Env[development]/File[/etc/puppetlabs/code/environments/development/manifests]/ensure: created

```

I'm currently using version 9.1.0 of the plugin.

Thanks for your help.

**Comment by alexjfisher** [comment]
Hi!  There are a couple of solutions.

You can set [`server_environments => []`](https://github.com/theforeman/puppet-puppet/tree/9.1.0#environments-support) or upgrade to version [11.0.0](https://github.com/theforeman/puppet-puppet/blob/master/CHANGELOG.md#1100-2019-01-14) of this module where this setting has been [removed](https://github.com/theforeman/puppet-puppet/pull/653).
