### ISSUE TITLE
Manage Puppet agent's connection timeout

### ISSUE THREAD

**Issue by Edmilson-JR** [theforeman/puppet-puppet#676]
Since Puppet 4, the Puppet agent's property `configtimeout` has been deprecated and shows a warning message during the execution.

As written at [Puppet documentation](https://puppet.com/docs/puppet/4.5/deprecated_settings.html#configtimeout), it has been replaced by `http_connect_timeout` and `http_read_timeout`, but I didtn't find those parameters at this module.

I know that if I don't pass value to the parameter [configtimeout](https://github.com/theforeman/puppet-puppet/blob/master/manifests/agent/config.pp#L19) I can avoid the warning.

But if I do this, how can I manage the agent's connections timeout?

As I mentioned above, I didn't find how to, so I made some [changes at my personal repository](https://github.com/Edmilson-JR/puppet-puppet/pull/1/files) - already tested - and it seems to solve the warning message.

If you're OK with those changes, I can do a PR.

Regards.

**Comment by ekohl** [comment]
Thanks for pointing that out. Had I known that, I'd have included it in the last breaking change where I dropped all pre-Puppet 4 code. I do notice you dropped the line ending at the end of files. Please ensure you keep those in.

**Comment by ekohl** [comment]
This has been merged in 22992c0a63138ffda783d2c4f6841c9768783357
