### ISSUE TITLE
Move certname configuration to [main]

### ISSUE THREAD

**Issue by baurmatt** [theforeman/puppet-puppet#680]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All?
- Ruby: All?
- Distribution: All?
- Module version: Current master

## How to reproduce (e.g Puppet code you use)
This is more of an Puppet problem, but I think we should solve it in this modules so other do not stumble over it...

```
root@3ca798133bc2:~# cat /etc/puppetlabs/puppet/puppet.conf
[agent]
certname = test
root@3ca798133bc2:~# puppet config print hostcert
/etc/puppetlabs/puppet/ssl/certs/3ca798133bc2.syseleven.net.pem
root@3ca798133bc2:~# sed -i 's,agent,main,' /etc/puppetlabs/puppet/puppet.conf
root@3ca798133bc2:~# puppet config print hostcert
/etc/puppetlabs/puppet/ssl/certs/test.pem
```

Conclusion: Puppet doesn't properly resolve the configured values which might lead to errors with config parameters depending on others.

The easiest solution seems to be putting `certname` in `[main]`. This is also what the documentation shows as examples --> https://puppet.com/docs/puppet/5.4/config_file_main.html

## What are you seeing
See above.

## What behaviour did you expect instead
Puppet would correctly determine the value of config parameters depending on $certname

**Comment by baurmatt** [comment]
I would suggest doing this:

```diff
diff --git a/manifests/agent/config.pp b/manifests/agent/config.pp
index f9b12d2..a25a3e5 100644
--- a/manifests/agent/config.pp
+++ b/manifests/agent/config.pp
@@ -32,7 +32,7 @@ class puppet::agent::config inherits puppet::config {
     }
   }
   if $::puppet::client_certname {
-    puppet::config::agent {
+    puppet::config::main {
       'certname':        value => $::puppet::client_certname;
     }
   }
```

If you're ok with it, I'm happy to provide a PR.

**Comment by ekohl** [comment]
While I agree putting it in main makes more sense, I would say doing this in `manifests/config.pp` feels more natural since there we configure the main section.

**Comment by baurmatt** [comment]
Ha, yeah that makes more sense! :) Are you ok with keeping the name $client_certname and moving the option into `puppet::config`?

**Comment by ekohl** [comment]
I did think about that and there's no better name IMHO since `$certname` is already reserved. It'd also make this a non-breaking change which I always like.
