### ISSUE TITLE
11.0.0 tagged incorrectly ?

### ISSUE THREAD

**Issue by dogjarek** [theforeman/puppet-puppet#687]
Hi,

It looks like you have few merged fixes for the version 11.0.0 are not tagged correctly.

There is one bug on windows in particular which keeps changing puppet.conf permissions to 644 what causes agent restart loop reported here https://github.com/theforeman/puppet-puppet/issues/678 and merged here https://github.com/theforeman/puppet-puppet/pull/679/commits/f12ec4906dd8df4ee477a277d64a39edd35023ce on the 13th of Feb. Version 11.0.0 was tagged on the 14th of Feb (so day after) and that fix hasn't become a part of it.

Was this an accident or intention ?

Thanks!

**Comment by ekohl** [comment]
This was likely an issue from my side. It's included in 11.0.1.
