### ISSUE TITLE
Dependency error after update (systemd)

### ISSUE THREAD

**Issue by dogjarek** [theforeman/puppet-puppet#695]
The latest version (12.0) of the module doesn't pull `camptocamp-systemd` module nor even mentiones it. Puppet run fails with the error:

`Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'systemd::dropin_file' (file: /etc/puppetlabs/code/environments/production/modules/puppet/manifests/server/puppetserver.pp, line: 196, column: 7) on `

It has to be added to the dependency list in metafile.

**Comment by ekohl** [comment]
https://github.com/theforeman/puppet-puppet/commit/27eb207440f450b7cfdbd678100b79e91031f4ce introduced this.

Technically it's a soft dependency, but there's no proper way to declare this in the Puppet ecosystem. We should have included it in the README. Would you be willing to come up with a patch?

**Comment by dogjarek** [comment]
Hi,

thanks for quick reply.

PR raised: https://github.com/theforeman/puppet-puppet/pull/696

I believe `metadata.json` contains the list of dependencies hence CLI tools `puppet module install` can recognise and download all dependencies needed.
