### ISSUE TITLE
How do I disable puppet agent in bulk (like it was possible in older versions with mcollective)

### ISSUE THREAD

**Issue by qaaditya** [theforeman/puppet-puppet#705]
Hello,

I upgraded puppetmaster to v2019.1.1, which does not support mcollective. In the older versions with mco, I was able to selectively disable puppet agents on nodes, by issuing a command from the CLI.

example: 
mco puppet disable -I /<nodename>/

I am wondering how the same can be accomplished in the latest version?

**Comment by ekohl** [comment]
I think that's more an issue for Puppet itself. This is just a module to manage the configuration. You can have a look at https://choria.io/ but this module manages neither mcollective nor choria.
