### ISSUE TITLE
puppet::server_version type is too strict for debian/ubuntu (apt)

### ISSUE THREAD

**Issue by jay7x** [theforeman/puppet-puppet#706]
I just tried to set specific server version today and hit into type check failed.
From what I see now in code
`puppet::version` is declared as string:
https://github.com/theforeman/puppet-puppet/blob/master/manifests/init.pp#L547
but `puppet::server_version` is declared with regex check:
https://github.com/theforeman/puppet-puppet/blob/master/manifests/init.pp#L636

So on ubuntu e.g. I cannot stick to specific puppetserver version as package version is '6.5.0-1xenial'.

I'd propose to use `String` type for `puppet::version` as well.

Thank you!

**Comment by ekohl** [comment]
Note there are two parameters: `server_version` (which is an `Optional[String]`) and `puppetserver_version` (which is the mentioned pattern). The former is to install an exact version and the one you're looking for. The second is to determine the behavior. Currently there's very little and it was much more when we still supported Puppetserver versions before 5.3.6.
