### ISSUE TITLE
puppetserver cipher suites must be upgraded

### ISSUE THREAD

**Issue by fschaer** [theforeman/puppet-puppet#714]
Hi,

I got a very hard time upgrading my puppetdb from 5.2 to 6.7.3-1.

According to documentation, if not specified, puppetdb will use "only non-DHE ciphers".
See : https://puppet.com/docs/puppetdb/latest/configure.html#cipher-suites

When starting in debug mode, I found that it in fact only accepts these keys on CentOS 7.7.1908 + jdk 1.8 : 

`2019-11-22T14:59:01.924+01:00 DEBUG [o.e.j.u.s.SslContextFactory] Selected Ciphers   [TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384] of [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
`

So in fact only TLS_DHE and TLS_ECDH keys are selected (everything before the " of ".

Thing is : the foreman module only configures the following keys by default : 

`[ 'TLS_RSA_WITH_AES_256_CBC_SHA256', 'TLS_RSA_WITH_AES_256_CBC_SHA', 'TLS_RSA_WITH_AES_128_CBC_SHA256', 'TLS_RSA_WITH_AES_128_CBC_SHA' ]`

This leads to cryptic `javax.net.ssl.SSLException: Received fatal alert: handshake_failure` and  `Puppet Error connecting to XXX on 8081 at route /pdb/cmd/v1?checksum` errors in puppetserver logs, and to `no ciphers in common` errors in puppetdb logs (debug mode for htttp connexions). And this breaks puppet(db)6 upgrades.

To keep compatibility, I'd suggest defaulting to a combination of the old and some new keys, possibly (not sure if the order matters) : 

`[ 'TLS_RSA_WITH_AES_256_CBC_SHA256', 'TLS_RSA_WITH_AES_256_CBC_SHA', 'TLS_RSA_WITH_AES_128_CBC_SHA256', 'TLS_RSA_WITH_AES_128_CBC_SHA', 'TLS_DHE_RSA_WITH_AES_128_GCM_SHA256', 'TLS_DHE_RSA_WITH_AES_256_GCM_SHA384', 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384', 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384' ]`

Changing the puppetserver (v6) cipher suites manually restores puppetdb connection after a puppetserver restart.

Regards

**Comment by ekohl** [comment]
I agree they're a bit outdated now. Could you come up with a PR that includes your suggestion?

**Comment by fschaer** [comment]
Just re-tested to make sure, and found out that it's not even sufficient to upgrade the puppetserver ciphers... damn. puppetdb 6.7 cipher-suites must also be specified to allow the same and current keys, otherwise some (not all) puppetdb queries still fail (?? uh ??)

Only the `/pdb/cmd/v1?checksum` queries fail.. definitely not a "yum update" as stated in puppetlabs docs ;)

I'll create try to create a PR a.s.a.p, I'm just unsure where the puppetdb changes should go, as the puppetdb is the puppetlabs... I'll check.

Regards
