### ISSUE TITLE
agent config dependent on agent install

### ISSUE THREAD

**Issue by term1n4l** [theforeman/puppet-puppet#724]
If you set agent config params such as environment or agent_noop etc, and set agent [install] to false, these config items are never put in place in the config. The agent install should not dictate the config of the agent. If you do not wish to update the agent package (which is already installed) but only the config then you shouldn't have to tell it to install the agent in order to update the config of the agent.

**Comment by term1n4l** [comment]
manage_packages param has the same effect. This is on Windows.

**Comment by term1n4l** [comment]
after I set manage_packages to false, this resolved the issue. Note that I had version and client_packages also set.

**Comment by ekohl** [comment]
> after I set manage_packages to false, this resolved the issue.

This is indeed exactly the intended workflow.
