### ISSUE TITLE
Puppetserver Restarts Every Time R10k is Run

### ISSUE THREAD

**Issue by witchbutter** [theforeman/puppet-puppet#725]
R10k in my environment is configured with webhooks to only pull 3 specific branches, and it cleans all others.  The issue is caused by this code:

params.pp
```
  $server_common_modules_path  = unique(["${server_envs_dir}/common", "${codedir}/modules", "${sharedir}/modules", '/usr/share/puppet/modules'])
```
server/config.pp
```
  if $::puppet::server::common_modules_path and !empty($::puppet::server::common_modules_path) {
    file { $::puppet::server::common_modules_path:
      ensure => directory,
      owner  => $::puppet::server_environments_owner,
      group  => $::puppet::server_environments_group,
      mode   => $::puppet::server_environments_mode,
    }
  }
```
Every time R10k runs it deletes `/etc/puppetlabs/code/environments/common` and then a few minutes later theforeman/puppet restores the folder and detects that as a config change and therefore restarts the puppetserver service.   This is extremely annoying because it makes the puppet master unavailable for a few minutes immediately after r10k deployed code causing inevitable run failures downstream for no good reason.

**Comment by witchbutter** [comment]
I am using this hack to prevent this behavior for the time being:
```
  exec { 'mark common code environment as immutable':
    command => '/usr/bin/chattr +i /etc/puppetlabs/code/environments/common',
    path    => '/bin:/sbin/:/usr/bin:/usr/sbin',
    user    => 'root',
    unless  => '/usr/bin/lsattr /etc/puppetlabs/code/environments | /bin/grep common | /bin/grep ^----i',
  }
```

**Comment by ekohl** [comment]
There's a parameter `puppet::server_common_modules_path` you can set (for example to an empty array) if you're not using this.

**Comment by ekohl** [comment]
Related issue: https://github.com/theforeman/puppet-puppet/issues/725
