### ISSUE TITLE
setup fileserver and add access rights to /etc/puppetlabs/puppetserver/conf.d/auth.conf

### ISSUE THREAD

**Issue by tepecat** [theforeman/puppet-puppet#752]
Hey,
I would like setup a fileserver and set access rights, https://puppet.com/docs/puppet/latest/file_serving.html

Atm I did not find a possibility to use this module to configure /etc/puppetlabs/puppetserver/conf.d/auth.conf to add an access  rule.

Did I not find the right parameter to configure auth.conf or is it atm not possible to add own config to auth.conf?

Best regards.
thomas.

**Comment by ekohl** [comment]
There is a parameter `auth_template` if you want full flexibility. Is that good enough?

**Comment by vchepkov** [comment]
It would be convenient to just add a rule. For example, this module is very useful
https://github.com/camptocamp/puppet-catalog-diff and one can't easily modify auth.conf to allow necessary access

**Comment by ekohl** [comment]
Since I don't use that, I don't have time to write a patch but will certainly accept a PR.

**Comment by tepecat** [comment]
thank you for your suggestions, I will try auth_template and puppet-catalog-diff.

**Comment by tepecat** [comment]
auth_template  is connected to ${puppet_dir}/auth.conf (see manifests/config.pp )and it is only useable, if use-legacy-auth-conf is true.
I am using use-legacy-auth-conf = false, so auth_template is not useable for new auth.conf (puppetserver/conf.d/auth.conf)

I add needed rule for my fileserver into templates/server/puppetserver/conf.d/auth.conf.erb now. Perhaps in a later version of this module it is possible to add additional rules into new auth.conf.

Thank you for your help!

**Comment by ekohl** [comment]
Ah, you're right. It does appear to be hardcoded:
https://github.com/theforeman/puppet-puppet/blob/f63fdaa5d3ad2850483d15fb752d2171de18f4b8/manifests/server/puppetserver.pp#L247-L250

Sadly, I don't have time to dive into this but a PR is welcome.

**Comment by chadh** [comment]
My use case is different, but relevant.  I need to update the allowed hosts for catalog, node, and report (we use a different node_name_fact than certname).  I think allowing the module user to provide a template for the puppetserver auth.conf is probably a good workaround for now.  Ideally maybe we would have types for building that file, but I know I don't have the cycles to implement that right now.
