### ISSUE TITLE
Appending values with puppet::config::entry is broken

### ISSUE THREAD

**Issue by dnlsng** [theforeman/puppet-puppet#759]
This commit, e87d8f2a7a008e2d92f5e41999fee83117edec25, breaks the ability to add multiple puppet::config::entry resources for the same key. By setting ensure_newline to true on the concat resource, a new line is added at the end of every fragment which removes the ability to append values. The appended values appear on the next line which results in a puppet config file which is not valid.

One way to resolve this would be to revert this commit and then add a concat fragment at the end of the file with just a single new line character.

**Comment by ekohl** [comment]
This was indeed mentioned @ https://github.com/theforeman/puppet-puppet/pull/707#issuecomment-546929749 but I never got around to reverting it.

A patch would be very welcome.

**Comment by dnlsng** [comment]
Sorry, I've been busy and only just had a chance to get around to a patch.
