### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [theforeman/puppet-puppet#760]
9 hard-coded secrets were found in 5 different scripts.

Script 1: https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/config.pp
 - Line [73](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/config.pp#L73): `key=value`

Script 2: https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp
 - Line [8](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp#L8): `user=puppet`
 - Line [83](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp#L83): `ssldir=/var/puppet/ssl`
 - Line [110](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp#L110): `ssldir=/etc/puppetlabs/puppet/ssl`
 - Line [129](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp#L129): `ssldir=/etc/puppetlabs/puppet/ssl`
 - Line [147](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/params.pp#L147): `ssldir=/var/lib/puppet/ssl`

Script 3: https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/agent/config.pp
 - Line [49](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/agent/config.pp#L49): `key=value`

Script 4: https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/agent/service/cron.pp
 - Line [18](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/agent/service/cron.pp#L18): `user=root`

Script 5: https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/server/config.pp
 - Line [101](https://github.com/theforeman/puppet-puppet/blob/04554efde21635f801a57a21441252344a07b6d7/manifests/server/config.pp#L101): `key=value`

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by ekohl** [comment]
This is just nonsense. These are not secrets but application configuration.
