### ISSUE TITLE
camptocamp-systemd is deprecated

### ISSUE THREAD

**Issue by AgileStas** [theforeman/puppet-puppet#802]
camptocamp-systemd module is deprecated since Aug 16th 2021, transfered to puppet-systemd.

Looks like the only change required is to change `"name": "camptocamp/systemd",` in metadata.json to `"name": "puppet/systemd",`

**Comment by ekohl** [comment]
Yes, we'll need to migrate over not just this module but all of our modules in theforeman's namespace. Would you be able to submit PRs for them? https://github.com/theforeman/foreman-installer-modulesync/blob/master/managed_modules.yml is a list, but not all of them depend on the systemd module.

**Comment by ekohl** [comment]
This was resolved in #804 but we forgot to close this out.
