### ISSUE TITLE
server::config class references wrong variable for additional_settings

### ISSUE THREAD

**Issue by unixsurfer** [theforeman/puppet-puppet#810]
I think [server::config](https://github.com/theforeman/puppet-puppet/blob/master/manifests/server/config.pp#L3) class uses the wrong variable for referencing to `additional_settings`.

In [this code](https://github.com/theforeman/puppet-puppet/blob/7534cbe648d6576509303da7be4f7724ee2d1fa4/manifests/server/config.pp#L100)  we configure additional settings for the `master` section and we use `$puppet::server_additional_settings` variable instead of `$puppet::server::additional_settings` variable:
```puppet
  $puppet::server_additional_settings.each |$key,$value| {
    puppet::config::master { $key: value => $value }
  }
```

Due to this the [additional_settings](https://github.com/theforeman/puppet-puppet/blob/master/manifests/server.pp#L401) parameter of `server` class is ignored.

**Comment by ekohl** [comment]
Somehow I missed this for a long time, but you're right so I opened https://github.com/theforeman/puppet-puppet/pull/874.
