### ISSUE TITLE
Sync up with upstream naming (`master`->`server`)

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-puppet#855]
Upstream has switched a bunch of the settings from `master` to `server` for various parts of the puppet server.  It would be nice if this module followed as I've no idea how long the old names will work.

**Comment by ekohl** [comment]
https://github.com/theforeman/puppet-puppet/pull/770 was opened but never finished. Needs a non-trivial rebase now and I'll admit that I lack the time to work on it, but PRs are welcome.
