### ISSUE TITLE
missing CRL `put` from `puppetserver/conf.d/auth.conf`

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-puppet#856]
Upstream currently provides the following stanza in their default `auth.conf`

```
         {
            match-request: {
                path: "^/puppet-ca/v1/certificate_revocation_list$"
                type: regex
                method: put
            }
            allow: {
               extensions: {
                   pp_cli_auth: "true"
               }
            }
            sort-order: 500
            name: "puppetlabs CRL update"
        },
```

Is this a new endpoint (and thus not in the templates) or removed on purpose?

**Comment by ekohl** [comment]
I think it's mostly an oversight we didn't include https://github.com/puppetlabs/puppetserver/commit/22ac4e5de772f57df561dbdc46c96daf4c14397f & https://github.com/puppetlabs/puppetserver/commit/d9bf097e0c0ee8a9df54490824016da1a2f07467
