### ISSUE TITLE
stdlib 9.x.x compat

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-puppet#877]
puppetlabs-stdlib released 9.x, can this module be updated to support that?

**Comment by jcpunk** [comment]
Since this uses puppet-puppetserver_foreman https://github.com/theforeman/puppet-puppetserver_foreman/issues/28 is relevant.

**Comment by vchepkov** [comment]
One of the spots that easy to overlook is templates:
https://github.com/theforeman/puppet-puppet/blob/master/templates/server/puppetserver/conf.d/auth.conf.erb#L16
That generates depreciation warnings with stdlib 8.6

**Comment by evgeni** [comment]
https://github.com/theforeman/puppet-puppet/commit/82e259598f40e259a642bd273435fa6323e30f04 fixed this
