### ISSUE TITLE
localconfig setting is deprecated

### ISSUE THREAD

**Issue by m8t** [theforeman/puppet-puppet#917]
Hello,

PR: https://github.com/theforeman/puppet-puppet/pull/918

I see that the module puppet injects a setting localconfig but is no where to be found in the code of Puppet.

In fact it has been deprecated see PUP-880 https://puppet.atlassian.net/browse/PUP-880

I think it is pretty safe to remove it.

Best,
Mike

**Comment by ekohl** [comment]
Oh wow, https://github.com/puppetlabs/puppet/commit/502720aa6cd8ca7eeeda27c002281d5d12df45de is 10 years old. We've been shipping something useless for a long time. Could you submit a PR instead of posting a patch?

**Comment by m8t** [comment]
Yes indeed, 2014 :'). I'm rusty, I will try it (not a big github user) :)

**Comment by m8t** [comment]
There we go: https://github.com/theforeman/puppet-puppet/pull/918
